name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: corepack enable
      - run: yarn install
      - run: yarn lint
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: corepack enable
      - run: yarn install
      - run: yarn build
      - run: yarn test
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: corepack enable
      - run: yarn install
      - run: yarn start:docker
      - run: yarn build
      # Borrowed from https://github.com/DCFoundation/cosmos-proposal-builder/blob/main/.github/workflows/pr.yml#L43-L61
      - name: Wait for Docker container to be ready
        run: |
          timeout 300 bash -c '
            TARGET_HEIGHT=1111
            SLEEP=10
            echo "Waiting for the Agoric service to be fully ready..."
            echo "Target block height: $TARGET_HEIGHT"
            while true; do
              response=$(curl --silent http://localhost:26657/abci_info);
              height=$(echo $response | jq -r ".result.response.last_block_height | tonumber");
              if [ "$height" -ge $TARGET_HEIGHT ]; then
                echo "Service is ready! Last block height: $height";
                break;
              else
                echo "Waiting for last block height to reach $TARGET_HEIGHT. Current height: $height";
              fi;
              sleep $SLEEP;
            done
          '
      - run: yarn start:contract
      - name: verify contracts started onchain
        run: |
          curl http://localhost:1317/agoric/vstorage/data/published.agoricNames.instance | grep orca
